### ISSUE TITLE
improve configuration handling of host related information, support multiple / different sites

### ISSUE THREAD

**Issue by partickl** [casualcore/casual-performance-test#3]
Configuration details regarding hostnames, ports etc is currently somewhat embedddn in python source files. We should create an abstraction for machine/host-related configuration that further separates code vs / configuration

Anothr nice feature would be the pssibility to handle diffrent sites with completely different hostnames and layout

A simple example/idea

siteA:
hosts:
  - alias: hostA
    user: user101
    hostname: abc.domain
    inbound-http-port: 8080
    inbound-gateway-port: 7070
  - alias: hostB
    user: user102
    ...
  
Testcases could then build and place casual-domains on these host-aliases with minimal knowledge of actual hostnames, ports etc

**Comment by ahhud** [comment]
@partickl I think inbound-http-port and inbound-gateway-port is more domain specific than node specific, i.e. there can be multiple domains and ports on one host.
But alias, user and hostname is relevant in site-config. But I think domain specific config also should be configurable in a yaml. My first take on the problem is to use this site.yaml as a "site_and_domain.yaml"

**Comment by partickl** [comment]
yes, you're right, it doesn't really belong in site specification. I think it would be good to clearly separate "machine/site"-config from domain related config
